name: "GraphQL Compose: Users"
description: "Enable to add user information to the schema."
type: module
core_version_requirement: ^10.1 || ^11
php: 8.1
dependencies:
  - drupal:user
  - graphql_compose:graphql_compose
package: GraphQL Compose
hidden: false

# Information added by Drupal.org packaging script on 2024-09-15
version: '2.2.1'
project: 'graphql_compose'
datestamp: 1726380161
